spring.application.name=Spring-Data-JPA

#Datasource properties
spring.datasource.url=jdbc:mysql://localhost:3306/sbms
spring.datasource.username=root
spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver #Depricated
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Dynamic table creation
spring.jpa.hibernate.ddl-auto=update

#To print the queries in console
spring.jpa.show-sql=true